[platformio]
default_envs = wbr_control
src_dir = ESP32/WBR_Control

[env:wbr_control]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
    hideakitai/ArduinoEigen
    bolderflight/Bolder Flight Systems SBUS@^8.1.4
    madhephaestus/ESP32Servo

[env:mpu6050_c3_test]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DMPU6050_STANDALONE_TEST=1
    -DMPU6050_SDA_PIN=8
    -DMPU6050_SCL_PIN=9
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:mpu6050_s3_test]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DMPU6050_STANDALONE_TEST=1
    -DMPU6050_SDA_PIN=10
    -DMPU6050_SCL_PIN=11
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:dual_motor_s3_test]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DWHEEL_MOTOR_STANDALONE_TEST=1
    -DHIP_SERVO_STANDALONE_TEST=0
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:combined_test]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DMPU6050_STANDALONE_TEST=0
    -DWHEEL_MOTOR_SOURCE_HARDWARE_TEST=0
    -DHIP_SERVO_MPU6050_COMBINED_TEST=1
    -DHIP_SERVO_STANDALONE_TEST=0
    -DWHEEL_MOTOR_STANDALONE_TEST=0
    -DARDUINO_USB_CDC_ON_BOOT=1
